### ISSUE TITLE
[Quest] V3

### ISSUE THREAD

**Issue by Windvis** [appuniversum/ember-appuniversum#422]
Track the work needed for the v3 release.

- [x] drop node 14 and 16 support, both are EOL (#453)
- [x] drop Ember 3.28 and 4.4 support. https://emberjs.com/releases/lts/ (#447)
- [x] remove deprecated code (#446)
- [x] Remove configuration flags (#446)
- [x]  Update dependencies to the newest version we can support (#454)
- [x] drop 4.8 support since that is also no longer supported (#457)

Nice to have:
- [ ] v2 addon conversion (#448)

**Comment by Windvis** [comment]
[Released](https://github.com/appuniversum/ember-appuniversum/releases/tag/v3.0.0) 🎉
